name: Test, lint, performance checks

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test, lint, performance checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore node_modules from cache
        uses: actions/cache@v3.0.11
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install project
        run: yarn

      - name: Run linter
        run: yarn lint

      - name: Run css linter
        run: yarn lint-style

      - name: Type check
        run: yarn type-check

      - name: Unit test
        run: yarn test:coverage

      - name: Check bundle size
        run: yarn build && ./node_modules/.bin/bundlesize
